model = "gpt-5.4-mini"
model_reasoning_effort = "medium"

# For codex_hooks
suppress_unstable_features_warning = true
plan_mode_reasoning_effort = "medium"

[projects."/home/ujihisa/git/fm"]
trust_level = "trusted"

[projects."/home/ujihisa/git/vancouversnowboarding.ca"]
trust_level = "trusted"

[projects."/home/ujihisa/git/config"]
trust_level = "trusted"

[projects."/home/ujihisa/git/monorepo"]
trust_level = "trusted"

<<<<<<< HEAD
[projects."/home/ujihisa/git/MechJeb2"]
trust_level = "trusted"

||||||| parent of e8eb490 (Minor tweaks)
=======
[notice]
hide_rate_limit_model_nudge = true

>>>>>>> e8eb490 (Minor tweaks)
[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
"gpt-5.1-codex-mini" = "gpt-5.4"

[sandbox_workspace_write]
network_access = true

[features]
codex_hooks = true
